name: Release

on:
  push:
    branches:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:

      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Import GPG signing key
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.RELEASES_GPG_PASSPHRASE }}
          passphrase: ${{ secrets.RELEASES_GPG_PRIVATE_KEY }}