name: Release

on:
  push:
    branches:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:

      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Java and Maven
        uses: actions/setup-java@v4
        with:
          java-version: 23
          distribution: 'temurin'
          cache: 'maven'
          check-latest: true
          server-id: 'ossrh' # must match the serverId configured for the nexus-staging-maven-plugin
          server-username: ${{ secrets.OSSRH_USERNAME }}
          server-password:  ${{ secrets.OSSRH_TOKEN }} # Env var that holds your OSSRH user pw
          gpg-private-key: ${{ secrets.RELEASES_GPG_PRIVATE_KEY }}

      - name: Publish to Apache Maven Central
        run: mvn deploy
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_TOKEN: ${{ secrets.OSSRH_TOKEN }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.RELEASES_GPG_PRIVATE_KEY }}