name: Trigger GitHub Actions CI

on:
  push:
    branches: "*"

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate GitHub App token
        id: gh_app
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.CENTRAL_CI_APP_ID }}
          private_key: ${{ secrets.CENTRAL_CI_APP_ID_APP_PRIVATE_KEY }}
          installation_id: ${{ secrets.CENTRAL_CI_APP_ID_INSTALLATION_ID }}

      - name: Trigger workflow in Repo B
        env:
          GH_TOKEN: ${{ steps.gh_app.outputs.token }}
        run: |
          gh workflow run parent-ci.yml \
            --repo sqldropper/github-actions \
            -f repo-url=${{ github.repository }} \
            -f branch=${{ github.ref_name }}